### ISSUE TITLE
A doubt about the OpTC dataset

### ISSUE THREAD

**Issue by wcl-sjtu** [C0ldstudy/Argus#2]
Hello, Thank you very much for sharing your work with us. I would be immensely grateful if you could also share the OpTC dataset exactly as it was used in the paper. It would be possible?

**Comment by C0ldstudy** [comment]
Thank you so much for your interest in our work! The OpTC dataset can be downloaded now by the [link](https://drive.google.com/drive/folders/1pTU-ZcyJbzoB1FuvujXe-ynaUy8O-PVD?usp=sharing).
